# Report

## 네이버만화 (https://comic.naver.com/index.nhn)
- 웹툰 - 장르별 추천 https://comic.naver.com/webtoon/genre.nhn
- 에피소드, 옴니버스, 스토리 별점순 상위 20개 추출

In [3]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

genres = ['episode', 'omnibus', 'story']  # 추출해야하는 장르 list

for genre in genres:    # genres에서 순차적으로 genre를 가져옴
  # 가져온 genre에 따라 해당 장르의 url에 접근하여 html 추출
  url = 'https://comic.naver.com/webtoon/genre?order=StarScore&view=image&genre={}'.format(genre)
  html = urlopen(url)
  bs = BeautifulSoup(html, 'html.parser')

  comic_list = bs.select('ul.img_list li')    # 추출한 html중에서 원하는 정보가 담겨 있는 부분만 가져옴

  data = [['Title']]  # 추출한 data를 저장할 list
  for comic in comic_list[:20]:   # comic_list에서 상위 20개만 순차적으로 가져옴
    comic_title = comic.select_one('dl dt a')['title'].strip()    # comic에서 title 정보만 가져옴
    data.append([comic_title])  # 추출한 data 저장

  # 추출된 data를 통해 dataframe 생성
  df = pd.DataFrame(data)
  df.columns = df.iloc[0]   
  
  # 생성된 dataframe 출력
  print("{} 장르 별점순 상위 20개".format(genre))
  display(df[1:])
  print("\n\n")

episode 장르 별점순 상위 20개

0       Title
1      슈퍼 시크릿
2      환생동물학교
3    오늘의 순정망화
4      마루는 강쥐
5      언럭키 맨션
6        수능일기
7   푸들과 Dog거중
8          겟백
9    선천적 얼간이들
10       노곤하개
11      홍차리브레
12   구름의 이동속도
13   웰캄투실버라이프
14     칼가는 소녀
15   대학원 탈출일지
16   나는 귀머거리다
17     1인용 기분
18   호랑이 들어와요
19       대학일기
20     모죠의 일지

omnibus 장르 별점순 상위 20개

0         Title
1        당신의 향수
2          귀전구담
3            내일
4            먹이
5        청춘 블라썸
6       죽음에 관하여
7         굿 리스너
8          소곤소곤
9           우바우
10      오민혁 단편선
11        조조코믹스
12    결혼생활 그림일기
13        먹는 인생
14         애옹식당
15        고고루키루
16     천리마 네버다이
17       히어로메이커
18         야자괴담
19  한 살이라도 어릴 때
20   아이들의 권 선생님

story 장르 별점순 상위 20개

0            Title
1              고래별
2            귀곡의 문
3     세기말 풋사과 보습학원
4          호러와 로맨스
5          모퉁이 뜨개방
6   [드라마원작] 치즈인더트랩
7             윈터우즈
8        야채호빵의 봄방학
9         악마와 계약연애
10          썸머 브리즈
11            여중생A
12           계룡선녀전
13           연의 편지
14           숲속의 담
15         동트는 로맨스
16    시월드가 내게 집착한다
17     이번 생도 잘 부탁해
18       야생천사 보호구역
19          마음의 숙제
20        늑대와 빨간모자